### ISSUE TITLE
Some files missing

### ISSUE THREAD

**Issue by DimLi777** [MartinLaza/OpenPRO58#8]
There is some files missing. How to solve?
--------------->
Arduino: 1.8.3 (Windows XP), Board: "Generic STM32F103C series, STM32F103CB (20k RAM. 128k Flash), Serial, 72Mhz (Normal), Smallest (default)"

In file included from C:\Documents and Settings\asasas\My Documents\Р—Р°РіСЂСѓР·РєРё\OpenPRO58-master\OpenPRO58-master\src\OpenPRO58\OpenPRO58.ino:14:0:

sketch\ui.h:5:26: fatal error: Adafruit_GFX.h: No such file or directory

 #include <Adafruit_GFX.h>

                          ^

compilation terminated.

exit status 1
Error compiling for board Generic STM32F103C series.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by piodabro** [comment]
This is fixed in my fork. I dont have my own PRO58 (it is in transit) but there is different development environment. Read the docs. If you can test it for me im waiting for feedback. Once its confirmed it works i will do the pull request.
https://github.com/piodabro/OpenPRO58

Today I also changed SPI from software to hardware version. not comitted yet.

**Comment by DimLi777** [comment]
I have tried your fork now, the same problem with some files missing. 
may be I have done something wrong?
1. connected gnd, vcc, tx, rx. boot connected to vdd, resistor removed.
2. erased memory with stm flasher
3. compiled "Pro58" folder with PIO
4. installed STM32 files to Arduino
5. connected to arduino for flashing, but there is file missing

**Comment by piodabro** [comment]
In my fork i dont use Arduino IDE.
Read the docs i said: https://github.com/piodabro/OpenPRO58/blob/master/Docs/setup_enviroment.md

After compiling You will have .pioenvs directory in OpenPRO58 dir.
next open genericSTM32F103CB dir, and there is firmware .bin file to flash.

**Comment by DimLi777** [comment]
Thanks! flashed bin with flash loader demonstrator and it is alive! But have some problems with video signal frequency 2 seconds after module switching on.

https://youtu.be/z08gImq4Q0c

**Comment by piodabro** [comment]
Today i've made new commit reverting software SPI support of receivers.
This is caused by swapped CLK and MOSI pins on module. The hardware SPI cannot be used then.
Try to update and build - flash again. It should fix that.

**Comment by DimLi777** [comment]
I have flash again now, but this problem still there. Looks like my module is broken, because once time it worked properly but after that all time with the issue.

**Comment by piodabro** [comment]
Double check what channel is set, and on what channel You are trasmitting signal.
Can you record video what happens on display after powering up?

**Comment by DimLi777** [comment]
Display show correct A1 channel the same as in the transmitter.
My module has a similar problem with the Eachine firmware too. That why I try to reflash new firmware.
https://youtu.be/0ldseh5I7GY

**Comment by piodabro** [comment]
And after flashing this firmware it behaves the same?
It look like firmware after starting does not set the channels on RX modules (via SPI).
Its hard to figure out without test device ;)
But after changing channel by toggle it works properly?
Could You show the flashed firware display?

**Comment by DimLi777** [comment]
Very strange, now the module behaves differently. It looks like something not calibrated correctly.
https://youtu.be/5YjryrVV0KI

**Comment by piodabro** [comment]
Did you calibrated RSSI in settings menu? This FW is port of https://github.com/sheaivey/rx5808-pro-diversity

**Comment by piodabro** [comment]
It should look similar to this: https://youtu.be/PRY-XF2qSRU?t=6m38s

**Comment by DimLi777** [comment]
Yes, all calibrated.
Now is the same as before. Look like it is hardware problem.
Not cost a waste time, this thing goes to garbage :)

**Comment by piodabro** [comment]
And on Your video, by toggling the switch You make the channel search not switching one by one. So this is why your channels and bands changes. Look at frequency - it is similar on changed channels. Module searches for channels with highest RSSI.

**Comment by piodabro** [comment]
Don't throw it out! This firmware is "work in progress", so some of things can not work properly. I think this is a firmware problem, and can be fixed. But i cant do this without the device im my hand. So we have to wait until it comes from China to Poland (im waiting for my package).

**Comment by DimLi777** [comment]
No I just change channels, after it find correct channel is show the noise. But after replug the power show normal picture. It look the the RX5808 modules is factory calibrated for 1-2 hz wrong. Because if it show picture, the quality of receiving wery weak.

**Comment by DimLi777** [comment]
need to have precise calibration as in the Achilles 2.0

**Comment by piodabro** [comment]
What i see is: 
1. On this video: https://www.youtube.com/watch?v=0ldseh5I7GY
the firmware does not set the channel on RX modules on power on, after setting it by hand it works.
2. On this video:  https://www.youtube.com/watch?v=5YjryrVV0KI
What channel did You set in TX? Please also look on frequencies (they can be different for RX an TX on the same channel marking ie A6 ;)

**Comment by piodabro** [comment]
Achilles is closed-source and cannot be ported to this STM32F103 MCU. Only owner of this project can do this.

**Comment by DimLi777** [comment]
1. yes, correct
2. A6 on the VTX and A6 on the Rreceiver. 
I've change the channel from A1 to A6 to check the picture after powering up. Because A1 is default RX5808 channel and it work without any switching.

**Comment by MartinLaza** [comment]
Try to increase the delay on firmware startup. Ať the moment there shall be 300ms. Without that the fw boots faster then rx5808 and first initial services channel command is not received correctly
